### ISSUE TITLE
Does not function

### ISSUE THREAD

**Issue by notasz** [oleksbard/brackets-custom-css#1]
Using Brackets 42 on OS X 10.10, created a new local CSS file, added code to alter most of the sidebar, activated it the CSS, saved the CSS file, and nothing happens. Tried reloading brackets, quitting and reopening, but it doesn't seem to want to work.

**Comment by oleksbard** [comment]
Hi @notasz. Does Brackets Developer Tools show any errors (`F12`) ? 
Also some selectors require `!important` flag to be set. In example:

```
.selector{
  color: red !important;
}
```

**Comment by notasz** [comment]
Hello. Yes, there is an error in the console that says it fails to load the specified CSS file. It looks like it's calling for the correct file name, but the pathing is messed up for some reason.

Here's the error from the console:
 Failed to load resource  file:///Users/asz/Library/Application%20Support/Brackets/extensions/user/dnbard.custom-css/services//Users/asz/Library/Application%20Support/Brackets/extensions/user/dnbard.custom-css/cache/5a9528fd-aac7-46da-a859-5710fab19720.css

**Comment by oleksbard** [comment]
Looks like this error is related to OS X. Unfortunately I have no expertise in this operating system. I'll be very glad if you help me fix this bug.  
Path for this CSS file is calculated in `config.js` and `services/initializer.js`

**Comment by notasz** [comment]
I'd be happy to help. I'll poke around and see if I can find where the issue is occurring.

**Comment by notasz** [comment]
I looked around the `initializer.js` and `config.js` and checked all the `path` definitions in each and they all point to the correct places. Based on the error it seems like the problem seems to be including the path to `initializer.js` when making a `get` request for the CSS file, but i'm unsure where exactly in the code this is happening. [This is the extended error for reference.](https://photos-2.dropbox.com/t/0/AAAugqO4DpCxpwrCbes2WEWoqWEx5mvDmKZvdNBc3bn9Kw/12/8216544/png/1024x768/3/1408046400/0/2/Screen%20Shot%202014-08-14%20at%2011.47.51%20AM.png/kuSDz3z6pWNa0o-A2mtLB4uJDukQOZpQan2_fnNYmQk)

**Comment by oleksbard** [comment]
@notasz looks like including CSS to Brackets IDE works differently on Windows and OS X. I'll try to solve this issue in future.

**Comment by notasz** [comment]
Thanks! I'll post again or make a pull request if I manage to fix it.

**Comment by notasz** [comment]
I was working on separate extension and noticed I was getting this same error when trying to use `loadStyleSheet();` API. I looked into the documentation for it and it notes that `loadStyleSheet();` loads a a style sheet _relative_ to the module. So when it attempts to load the style sheet given entire path of a file, it begins with the root directory of the working file (in the case of `initializer.js` on OS X that is `file:///Users/asz/Library/Application%20Support/Brackets/extensions/user/brackets-custom-css/services`  and then tries to reference the entire path for the CSS file from that directory.

Given that the `loadStyleSheet();` API should only be able to reference files inside the `module` directory, i'm not entirely sure why this extension would work in Windows/Linux but not on OS X. This may be a bug with brackets between different OS versions and i'm not sure wether or not there is an easy workaround.

**Comment by oleksbard** [comment]
I have a same feelings about that. I`ll make changes to the code (to use relative paths) and then ask you to test them on OS X.

**Comment by oleksbard** [comment]
@notasz I've made a commit 71f5e7425abfef2d90e830064703d6577321553a with fixes. Could you please test it on OS X ?

**Comment by notasz** [comment]
Tested on OSX 10.10, your fix works. No more pathing errors in the console, and CSS from enabled files is applied on file save. Good work. :)

**Comment by oleksbard** [comment]
Good news!
